export const SEND_PANIC_REQUEST_SUCCESS = "SEND_PANIC_REQUEST_SUCCESS";
export const SEND_PANIC_REQUEST_FAILURE = "SEND_PANIC_REQUEST_FAILURE";
export const CANCEL_PANIC_REQUEST = "CANCEL_PANIC_REQUEST";
export const LOAD_PANIC_HISTORY = "LOAD_PANIC_HISTORY";
