export const SEND_PANIC_REQUEST_SUCCESS = "SEND_PANIC_REQUEST_SUCCESS";
export const SEND_PANIC_REQUEST_FAILURE = "SEND_PANIC_REQUEST_FAILURE";
export const CANCEL_PANIC_REQUEST_SUCCESS = "CANCEL_PANIC_REQUEST_SUCCESS";
export const CANCEL_PANIC_REQUEST_FAILURE = "CANCEL_PANIC_REQUEST_FAILURE";
export const LOAD_PANIC_HISTORY_IN_PROGRESS = "LOAD_PANIC_HISTORY_IN_PROGRESS";
export const LOAD_PANIC_HISTORY_SUCCESS = "LOAD_PANIC_HISTORY_SUCCESS";
export const LOAD_PANIC_HISTORY_FAILURE = "LOAD_PANIC_HISTORY_FAILURE";
